:set nocompatible
:syntax on
:set number
:set fileencoding=utf-8
:set background=dark
:set ruler
:set showcmd
:set tabstop=4
:set wrap
:set shiftwidth=4
:set noexpandtab
:set autoindent
:set smartindent
:set copyindent
:set smarttab
:set shiftround
:set showmatch
:set title
:set textwidth=80
